server:
  port: 8080

spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: sampletest1
    password: sampletest1
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

app:
  security:
    iam:
      issuer-uri: http://localhost:8180/realms/company-realm
      jwk-set-uri: http://localhost:8180/realms/company-realm/protocol/openid-connect/certs

logging:
  level:
    org.springframework.security: INFO